{{- if ((.Values.tls).enabled) }}
# tls:
#   enabled: true
#   name: wildcardlocal-tls
#   crtFile: certs/tls-wildcard.crt
#   keyFile: certs/tls-wildcard.key
apiVersion: v1
kind: Secret
metadata:
  name: {{ default "secret-tls" .Values.tls.name }}
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/tls
data:
{{- $crtFile := default "tls.crt" .Values.tls.crtFile }}
{{- $keyFile := default "tls.key" .Values.tls.keyFile }}
  tls.crt: {{ .Files.Get $crtFile | b64enc }}
  tls.key: {{ .Files.Get $keyFile | b64enc }}
{{- end }}